# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15776570ba1a35d7d594a04ab66006c3df7f96ad3235e7c30d64d56b9c5da1579fc7c4650c133c9e7c31fc3762e734c1d22b0ee65f9e4b30798668625f033428

test:
  secret_key_base: 0d34dba997e6d24d3adb34087442819f2659d111cf42b541b4675c4f933c84bf430187a2c8972c2d7a088f86a2470d9913f1ff83f6b30a449b6d5214d341f1ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
